### ISSUE TITLE
Problem with "make bin/julia"

### ISSUE THREAD

**Issue by ys7914** [HPCE/hpce-2017-cw1#47] opened 2017-10-16 20:06 UTC
I am using Windows with MinGW (with gcc and g++) and git installed. I have set the environment variables properly so gcc and g++ works. I made a copy of _mingw32-make.exe_ and renamed it to _make.exe_ in the _C:\MinGW\bin_ folder.

I navigated to some folder through cmd.exe, cloned the _hpce-2017-cw1_ folder from github using **git clone https://github.com/HPCE/hpce-2017-cw1.git** command to get the latest code. Navigated into the _hpce-2017-cw1_ folder and tried to execute the **make bin/julia** command. It throws an error.
<img width="960" alt="cw1-issue1" src="https://user-images.githubusercontent.com/25391124/31632528-1e732048-b2b5-11e7-8d6c-85ac10da4936.png">

What is the issue here and how do I solve this problem?

**Comment by m8pple** [comment] 2017-10-16 20:26
Closed as duplicate of #47. Please see the response there.

**Closed as completed by m8pple** 2017-10-16 20:26 UTC
